# THIS WAS GENERATED BY CLAUDE

from PySide6.QtWidgets import (
    QApplication, QMainWindow, QTreeWidget, QTreeWidgetItem, QVBoxLayout, QWidget
)
from PySide6.QtGui import QIcon, QColor
from PySide6.QtCore import Qt
import sys


# ─────────────────────────────────────────
#  Fake file system structure
# ─────────────────────────────────────────
FILE_SYSTEM = [
    ("Assets/", [
        ("Textures/", [
            ("grass.png",   "12 KB"),
            ("stone.png",   "8 KB"),
            ("water.png",   "15 KB"),
        ]),
        ("Audio/", [
            ("bgm_main.ogg",    "2.4 MB"),
            ("sfx_jump.wav",    "40 KB"),
            ("sfx_land.wav",    "38 KB"),
        ]),
        ("Fonts/", [
            ("Roboto-Regular.ttf",  "160 KB"),
            ("Roboto-Bold.ttf",     "158 KB"),
        ]),
    ]),
    ("Scripts/", [
        ("Player/", [
            ("player_controller.py",    "4 KB"),
            ("player_stats.py",         "2 KB"),
        ]),
        ("Enemies/", [
            ("base_enemy.py",   "3 KB"),
            ("slime.py",        "1 KB"),
            ("goblin.py",       "2 KB"),
        ]),
        ("main.py",     "1 KB"),
        ("settings.py", "512 B"),
    ]),
    ("Scenes/", [
        ("MainMenu.scene",  "6 KB"),
        ("Level_01.scene",  "22 KB"),
        ("Level_02.scene",  "19 KB"),
    ]),
    ("Config/", [
        ("project.cfg",     "1 KB"),
        ("input_map.cfg",   "2 KB"),
        ("keybinds.cfg",    "512 B"),
    ]),
    ("Docs/", [
        ("Design/", [
            ("GDD.md",          "48 KB"),
            ("art_style.md",    "12 KB"),
        ]),
        ("README.md",   "3 KB"),
        ("CHANGELOG.md","8 KB"),
    ]),
]

FOLDER_COLOR = QColor("#6EA8D6")   # blue-ish for folders
FILE_COLOR   = QColor("#C8C8C8")   # grey for files


def build_tree(parent, entries: list) -> None:
    """
    Recursively builds QTreeWidgetItems from the FILE_SYSTEM structure.
    Each entry is either:
      (name, list)       → folder
      (name, size_str)   → file
    """
    for entry in entries:
        name, content = entry

        if isinstance(content, list):
            # ── Folder ──────────────────────────────
            item = QTreeWidgetItem(parent, [name, ""])
            item.setForeground(0, FOLDER_COLOR)
            item.setExpanded(True)          # start expanded so everything is visible
            build_tree(item, content)       # recurse into children

        else:
            # ── File ────────────────────────────────
            size = content
            item = QTreeWidgetItem(parent, [name, size])
            item.setForeground(0, FILE_COLOR)
            item.setForeground(1, QColor("#888888"))


class FileSystemDemo(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("QTreeWidget — File System Demo")
        self.resize(500, 600)
        self.setStyleSheet("""
            QMainWindow, QWidget {
                background: #1e1e2e;
            }
            QTreeWidget {
                background: #1e1e2e;
                color: #cdd6f4;
                border: 1px solid #313244;
                font-family: "Consolas", "Courier New", monospace;
                font-size: 13px;
            }
            QTreeWidget::item {
                padding: 2px 4px;
            }
            QTreeWidget::item:hover {
                background: #313244;
            }
            QTreeWidget::item:selected {
                background: #45475a;
                color: #cdd6f4;
            }
            QHeaderView::section {
                background: #181825;
                color: #6c7086;
                padding: 4px 8px;
                border: none;
                border-bottom: 1px solid #313244;
                font-size: 11px;
                text-transform: uppercase;
                letter-spacing: 1px;
            }
            QScrollBar:vertical {
                background: #181825;
                width: 8px;
            }
            QScrollBar::handle:vertical {
                background: #45475a;
                border-radius: 4px;
            }
        """)

        # ── Tree Widget setup ────────────────────────
        self.tree = QTreeWidget()
        self.tree.setColumnCount(2)
        self.tree.setHeaderLabels(["Name", "Size"])
        self.tree.setColumnWidth(0, 320)
        self.tree.setIndentation(18)
        self.tree.setAnimated(True)             # smooth expand/collapse

        # ── Populate ─────────────────────────────────
        build_tree(self.tree, FILE_SYSTEM)

        # ── Layout ───────────────────────────────────
        container = QWidget()
        layout = QVBoxLayout(container)
        layout.setContentsMargins(8, 8, 8, 8)
        layout.addWidget(self.tree)
        self.setCentralWidget(container)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = FileSystemDemo()
    window.show()
    sys.exit(app.exec())